---
- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Caddy
  ansible.builtin.service:
    name: caddy
    state: restarted

- name: Reload Caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
