---
- name: Sudo Diagnosis Playbook
  hosts: gen8
  gather_facts: no  # This bypasses the heavy 'setup' module that is timing out
  tasks:
    - name: Can I run a command as a normal user?
      command: whoami
      become: no
      register: user_result

    - name: Show normal user
      debug:
        msg: "Current user is {{ user_result.stdout }}"

    - name: Can I run a command as root? (The Sudo Test)
      command: whoami
      become: yes
      register: root_result

    - name: Show root user
      debug:
        msg: "Elevated user is {{ root_result.stdout }}"
