---
common_packages:
  - micro
  - rsync
  - git
  - zfsutils-linux
  - podman
  - buildah
  - slirp4netns

common_diagnostic_packages:
  - smartmontools
  - nvme-cli
  - htop
  - iotop

common_quadlet_dir: /etc/containers/systemd
