---
- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Vykar
  ansible.builtin.service:
    name: vykar-server
    state: restarted

- name: Reload Caddy
  ansible.builtin.command: systemctl reload-or-restart caddy
  async: 30
  poll: 5
