---
security_ssh_port: 22
security_forgejo_ssh_port: 2222
security_ufw_tcp_ports:
  - "{{ security_ssh_port }}"
  - "80"
  - "443"
  - "{{ security_forgejo_ssh_port }}"

security_fail2ban_bantime: 1h
security_fail2ban_findtime: 10m
security_fail2ban_maxretry: 5
